#!/bin/bash

# Copyright 2016, 2019 Guillaume Bernard <contact@guillaume-bernard.fr>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

typeset -r LIBSHELL_DIR="${HOME}/.local/lib/libShell"
typeset -r SHELLCONFIG_CONF="${HOME}/.shellConfig.conf"
typeset -r SHELLCONFIG_CONF_DIR="${HOME}/.shellConfig"
typeset -r SHELLCONFIG_CUSTOM_SCRIPTS_DIR="${HOME}/.shellConfig.external"

# Load the libShell framework
if [ -e "${LIBSHELL_DIR}/libShell.sh" ]; then
    source "${LIBSHELL_DIR}/libShell.sh"
else
    printf "\e[31mERR: libShell must be installed under $(dirname ${LIBSHELL_DIR}) directory!\e[39m"
fi

# Load the shellConfig configuration file
[[ -f "${SHELLCONFIG_CONF}" ]] && source "${SHELLCONFIG_CONF}"

# Load shellConfig itself
if [[ -d "${SHELLCONFIG_CONF_DIR}" ]]; then
    Log ${DEBUG} "Loading shellConfig…"
    for file in "${SHELLCONFIG_CONF_DIR}"/*.sh; do
        source "${file}"
    done
fi

# Load custom scripts
if [[ -d ${SHELLCONFIG_CUSTOM_SCRIPTS_DIR} ]]; then
    Log ${DEBUG} "Loading custom scripts…"
    for file in "${SHELLCONFIG_CUSTOM_SCRIPTS_DIR}"/*.sh; do
        source "${file}"
    done
fi

